<!-- Formulaire d'inscription à la newsletter -->
<h1>Inscris toi à la newletter pour ne pas louper les dernières nouveautés</h1>
<form>
    <fieldset>
        <!-- Champ de saisie pour l'adresse email -->
        <label for="email">Email</label>
        <input type="text" name="email" id="email" />
    </fieldset>
    <fieldset>
        <!-- Bouton de soumission du formulaire -->
        <input type="submit" value="Je m'inscris" />
    </fieldset>
</form>
<section>
    <h2>Affichage de l'image pour la newsletter</h2>
    <figure>
        <h3>Affichage de l'image</h3>
        <img src="/res03-projet-final/assets/img/images-de-fond/Death_Note,_Book.svg" alt="image de death note">
    </figure>
</section>