<!-- Formulaire d'inscription à la newsletter -->
<h1>Inscris toi à la newletter pour ne pas louper les dernières nouveautés</h1>
<fieldset>
    <!-- Champ de saisie pour l'adresse email -->
    <label for="email">Email</label>
    <input type="text" name="email" id="email" />
</fieldset>
<fieldset>
    <!-- Bouton de soumission du formulaire -->
    <input type="submit" value="Je m'inscris" />
</fieldset>
