<!-- Formulaire d'inscription à la newsletter -->
<h1>Inscris toi à la newletter pour ne pas louper les dernières nouveautés</h1>
<form>
    <fieldset>
        <!-- Champ de saisie pour l'adresse email -->
        <label for="email">Email</label>
        <input type="text" name="email" id="email" />
    </fieldset>
    <fieldset>
        <!-- Bouton de soumission du formulaire -->
        <input type="submit" value="Je m'inscris" />
    </fieldset>
</form>
<section>
    <figure>
        <img src="https://upload.wikimedia.org/wikipedia/commons/b/b5/Death_Note%2C_Book.svg" alt="image de death note">
    </figure>
</section>