<section>
    <h1>Liste des catégories</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nom</th>
                <th scope="col">Image</th>
                <th scope="col">Caption</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data['categories'] as $category) { ?>
            <tr>
                <td><?= $category['id']; ?></td>
                <td><?= $category['title']; ?></td>
                <td>
                    <figure>
                        <img src="<?= $category['URL']; ?>" alt="image de la catégorie">
                    </figure>
                </td>
                <td><?= $category['caption']; ?></td>
                <td><?= $category['description']; ?></td>
                <td>
                    <a href="/res03-projet-final/admin/categories/update/<?= $category['id']; ?>">Modifier</a>
                    <a href="/res03-projet-final/admin/categories/delete/<?= $category['id']; ?>">Supprimer</a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</section>