<h1>Inscription</h1>
<form method="post" action="creation">
    <fieldset>
        <label for="username">Pseudo</label>
        <input type="text" name="username" id="username" />
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="text" name="email" id="email" />
    </fieldset>
    <fieldset>
        <label for="firstname">Prénom</label>
        <input type="text" name="first_name" id="firstname" />
    </fieldset>
    <fieldset>
        <label for="lastname">Nom</label>
        <input type="text" name="last_name" id="lastname" />
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password" />
    </fieldset>
    <fieldset>
        <label for="confirmpassword">Confirmation mot de passe</label>
        <input type="password" name="confirmpassword" id="confirmpassword" />
    </fieldset>
    <fieldset>
        <label for="birthday">Anniversaire</label>
        <input type="date" name="birthday" id="birthday" />
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" value="creation">
    </fieldset>
    <fieldset>
        <input type="submit" value="Je crée mon compte" />
    </fieldset>
    
    <p>Clique <a href="../connexion/connexion.phtml">ici</a> pour te connecter</p>
</form>
