<footer id="footer">
    <section>
        <figure>
            <img src="/res03-projet-final/assets/img/logo2.png" alt="Le logo de mon site.">
        </figure>
    </section>
    <section>
        <a href="info"><h2>À propos</h2></a>
    </section>
    <section>
        <a href="mon-compte"><h2>Mon compte</h2></a>
    </section>
    <section>
        <h2>Inscrivez vous à la newsletter</h2>
    </section>
</footer>