<footer id="footer">
    <!-- Section avec le logo du site -->
    <section>
        <figure>
            <img src="/res03-projet-final/assets/img/logo2.png" alt="Le logo de mon site.">
        </figure>
    </section>
    
    <!-- Section "À propos" avec des infos du site -->
    <section>
        <a href="/res03-projet-final/info"><h2>À propos</h2></a>
    </section>
    
    <!-- Section "Contact" -->
    <section>
        <a href="/res03-projet-final/contact"><h2>Contact</h2></a>
    </section>
    
    <!-- Section "Inscrivez vous à la newsletter" pour recevoir les dernières nouveautés -->
    <section>
        <a href="/res03-projet-final/newsletter"><h2>Inscrivez vous à la newsletter</h2></a>
    </section>
    
    <!-- Section "Espace administrateur" accessible que par l'administrateur, bloqué pour les customers -->
    <section>
        <a href="/res03-projet-final/admin"><span class="fa-regular fa-user"></span>  Espace administrateur</a>
        <!-- Utilisation d'une icône d'utilisateur de la bibliothèque d'icônes Font Awesome -->
    </section>
</footer>
