<header id="header">
    <ul>
        <li><a href="/res03-projet-final/accueil">ACCUEIL</a></li>
        <li><a href="/res03-projet-final/liste-categories">LICENCES</a></li>
    </ul>
    <figure>
        <img src="/res03-projet-final/assets/img/logo2.png" alt="Le logo de mon site.">
    </figure>
    <ul>
        <li><a href="/res03-projet-final/creation">INSCRIPTION</a></li>
        <li><a href="/res03-projet-final/connexion">CONNEXION</a></li>
        <li><a href="/res03-projet-final/panier"><span class="fa fa-shopping-cart"></span></a></li>
    </ul>
</header>