<!-- Header pour les personnes pas connectées -->
<header id="header">
    <!-- Première liste de liens -->
    <ul>
        <li><a href="/res03-projet-final/accueil">ACCUEIL</a></li>
        <li><a href="/res03-projet-final/liste-categories">LICENCES</a></li>
    </ul>
    <!-- Logo du site -->
    <figure>
        <img src="/res03-projet-final/assets/img/images-de-fond/logo2.png" alt="Le logo de mon site.">
    </figure>
    <!-- Deuxième liste de liens -->
    <ul>
        <li><a href="/res03-projet-final/creation">INSCRIPTION</a></li>
        <li><a href="/res03-projet-final/connexion">CONNEXION</a></li>
        <li><a href="/res03-projet-final/panier"><span class="fa fa-shopping-cart"></span></a></li>
        <!-- Utilisation d'une icône de panier de la bibliothèque d'icônes Font Awesome -->
    </ul>
</header>