<header id="header">
    <ul>
        <li><a href="acceuil">ACCUEIL</a></li>
        <li><a href="licences">LICENCES</a></li>
    </ul>
    <figure>
        <img src="/res03-projet-final/assets/img/logo2.png" alt="Le logo de mon site.">
    </figure>
    <ul>
        <li><a href="creation">INSCRIPTION</a></li>
        <li><a href="connexion">CONNEXION</a></li>
        <li><a href="panier"><span class="fa fa-shopping-cart"></span></a></li>
    </ul>
</header>