<!-- Header pour les personnes connectées -->
<header id="header">
    <!-- Première liste de liens -->
    <ul>
        <li><a href="/res03-projet-final/accueil">ACCUEIL</a></li>
        <li><a href="/res03-projet-final/liste-categories">LICENCES</a></li>
    </ul>
    
    <!-- Logo du site -->
    <figure>
        <img src="/res03-projet-final/assets/img/images-de-fond/logo2.png" alt="Le logo de mon site.">
    </figure>
    
    <!-- Deuxième liste de liens avec apparition du lien mon compte bloqué quand on est pas connecté -->
    <ul>
        <li><a href="/res03-projet-final/nouveautes">NOUVEAUTÉS</a></li>
        <li><a href="/res03-projet-final/mon-compte">MON COMPTE</a></li>
        <li><a href="/res03-projet-final/panier"><span class="fa fa-shopping-cart"></span></a></li>
        <!-- Utilisation d'une icône de panier de la bibliothèque d'icônes Font Awesome -->
    </ul>
</header>
