<section>
    <!-- Tableau des produits -->
    <h1>Liste des produits</h1>
    
    <!-- Bouton pour créer un nouveau produit -->
    <a href="/res03-projet-final/admin/products/create" class="btn btn-primary">Créer un produit</a>
    
    <!-- Tableau qui affiche tous les produits -->
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Image</th>
                <th scope="col">Caption</th>
                <th scope="col">Description</th>
                <th scope="col">Prix</th>
                <th scope="col">Licence</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data['products'] as $product) { ?>
            <tr>
                <!-- Nom du produit -->
                <td><?= $product['name']; ?></td>
                
                <!-- Image du produit -->
                <td>
                    <figure>
                        <img src="<?= $product['URL']; ?>" alt="<?= $product['caption']; ?>" class="img-fluid">
                    </figure>
                </td>
                
                <!-- Caption de l'image -->
                <td><?= $product['caption']; ?></td>
                
                <!-- Description du produit -->
                <td><?= nl2br($product['description']); ?></td>
                
                <!-- Prix du produit -->
                <td><?= $product['price']; ?></td>
                
                <!-- Licence du produit -->
                <td><?= $product['title']; ?></td>
                
                <!-- Deux boutons pour chaque utilisateur : Modifier et Supprimer -->
                <td>
                    <a href="/res03-projet-final/admin/products/update/<?= $product['id']; ?>" class="btn btn-primary">Modifier</a>
                    <a href="/res03-projet-final/admin/products/delete/<?= $product['id']; ?>" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</section>
