<section>
    <h1>Liste des utilisateurs</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/res03-projet-final/admin/users/addresses">Avec adresses<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin/users">Sans adresses</a>
                </li>
            </ul>
        </div>
    </nav>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Pseudo</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Email</th>
                <th scope="col">Adresse</th>
                <th scope="col">Mot de passe</th>
                <th scope="col">Date d'inscription</th>
                <th scope="col">Date d'anniversaire</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data['users'] as $user) { ?>
            <tr>
                <td><?= $user['username']; ?></td>
                <td><?= $user['first_name']; ?></td>
                <td><?= $user['last_name']; ?></td>
                <td><?= $user['email']; ?></td>
                <td><?= $user['number'] . ' ' . $user['street'] . ' ' . $user['postal_code'] . ' ' . $user['city']; ?></td>
                <td><?= $user['password']; ?></td>
                <td><?= $user['registration_date']; ?></td>
                <td><?= $user['birthday']; ?></td>

                <td>
                    <a href="/res03-projet-final/admin/users/addresses/update/<?= $user['id']; ?>" class="btn btn-primary">Modifier</a>
                    <a href="/res03-projet-final/admin/users/addresses/delete/<?= $user['id']; ?>" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</section>