<h1>Connexion</h1>
<form method="post" action="connexion">
    <fieldset>
        <label for="username">Pseudo</label>
        <input type="text" name="username" id="username" />
    </fieldset>
    <fieldset>
        <label for="password1">Mot de passe</label>
        <input type="password" name="password" id="password1" />
    </fieldset>
    <Fieldset>
        <input type="hidden" name="formName" value="connexion">
    </Fieldset>
    <fieldset>
        <input type="submit" value="Je me connecte" />
    </fieldset>
    
    <p>Clique <a href="../creation/creation.phtml">ici</a> pour créer un compte</p>
</form>