<h1>Connexion</h1>
<form method="post" action="">
    <fieldset>
        <label for="username">Pseudo</label>
        <input type="text" name="username" id="username" />
    </fieldset>
    <fieldset>
        <label for="password1">Mot de passe</label>
        <input type="password" name="password" id="password1" />
    </fieldset>
    <fieldset>
        <input type="submit" value="Je me connecte" />
    </fieldset>
</form>