<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand">ADMIN</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/res03-projet-final/admin">Accueil<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin/categories">Licences</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin/products">Produits</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin/users">Utilisateurs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/res03-projet-final/admin/orders">Commandes</a>
                </li>
            </ul>
        </div>
    </nav>
</header>