<h1><?= $data["category"]->getTitle(); ?></h1>

<?php foreach($data["products"] as $product) {
    
    $categoryManager = new CategoryManager();
    $productManager = new ProductManager();
    $categorySlug = $categoryManager->createSlug($data["category"]->getTitle());
    $productObject = $productManager->getProductById($product["id"]); ?>
    
    <article>
        <a href="https://anthonycormier.sites.3wa.io/res03-projet-final/liste-categories/<?= $categorySlug ?>/<?= $productObject->getId() ?>"><img src="<?= $product["URL"] ?>"></a>
        <h2><a href="https://anthonycormier.sites.3wa.io/res03-projet-final/liste-categories/<?= $categorySlug ?>/<?= $productObject->getId() ?>"><?= $productObject->getName() ?></a></h2>
    </article>
    
<?php } ?>