<h1>Formulaire de modification du produit</h1>
<form method="post" action="/res03-projet-final/admin/products/update/<?= $data["product"]->getId(); ?>">
    <fieldset class="my-3">
        <label for="name">Nom</label>
        <input type="text" class="form-control" name="name" id="name" required value="<?= $data["product"]->getName(); ?>"/>
    </fieldset>
    <fieldset class="my-3">
        <label for="description">Description</label>
        <textarea name="description" class="form-control" rows="5" cols="30"><?= $data["product"]->getDescription(); ?></textarea>
    </fieldset>
    <fieldset class="my-3">
        <label for="price">Prix</label>
        <input type="number" class="form-control" name="price" id="price" required value="<?= $data["product"]->getPrice(); ?>"/>
    </fieldset>
    <fieldset class="my-3">
        <label for="URL">URL de l'image</label>
        <input type="URL" name="URL" class="form-control" id="URL" required value="<?= $data["picture"]->getURL(); ?>"/>
    </fieldset>
    <fieldset class="my-3">
        <label for="caption">Caption</label>
        <input type="text" name="caption" class="form-control" id="caption" value="<?= $data["picture"]->getCaption(); ?>"/>
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" value="update-product">
    </fieldset>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>