<?php
// Initialisation d'un objet CategoryManager pour créer des slugs
$categoryManager = new CategoryManager();
// Création du slug à partir du titre de la catégorie
$categorySlug = $categoryManager->createSlug($data['category']->getTitle()); ?>

<a href="/res03-projet-final/liste-categories/$categorySlug" class="retour-btn"><< Retour à la page de <?=$data['category']->getTitle(); ?></a>

<section>
    <section>
        <figure>
            <?php if (count($data['pictures']) > 0) { ?>
                <img src="<?php echo $data['pictures'][0]->getURL(); ?>" alt="<?php echo $data['pictures'][0]->getCaption(); ?>">
            <?php } ?>
        </figure>
    </section>
    <section>
        <section>
            <h1><?php echo $data['product']->getName(); ?></h1>
            <p>Prix : <?php echo $data['product']->getPrice(); ?> €</p>
            <p>Catégorie : <?php echo $data['category']->getTitle(); ?></p>
        </section>
        <section>
            <p><?php echo $data['product']->getDescription(); ?></p>
        </section>
        
        <section>
            <form method="post" action="/res03-projet-final/panier">
                <input type="hidden" name="product_id" value="<?php echo $data['product']->getId(); ?>">
                <input type="number" name="quantity" id="quantity" value="1" min="1">
                <button class="paniers" data-product-id="<?php echo $data['product']->getId(); ?>">Ajouter au panier</button>
            </form>
        </section>
    </section>
</section>
