<h1>Bienvenue sur la page admin</h1>
<p class="mblank-auto">Clique ici pour afficher la liste des licences</p>
<a href="/res03-projet-final/admin/categories" class="btn btn-primary">Licences</a>
<p class="my-3">Clique ici pour modifier la liste des produits</p>
<a href="/res03-projet-final/admin/products" class="btn btn-primary">Produits</a>
<p class="my-3">Clique ici pour modifier la liste des utilisateurs</p>
<a href="/res03-projet-final/admin/users" class="btn btn-primary">Utilisateurs</a>
<p class="my-3">Clique ici pour modifier la liste des commandes</p>
<a href="/res03-projet-final/admin/orders" class="btn btn-primary">Commandes</a>