<!-- Accueil de la page admin -->
<h1>Bienvenue sur la page admin</h1>

<!-- Lien vers la liste des licences -->
<p class="mblank-auto">Clique ici pour afficher la liste des licences</p>
<a href="/res03-projet-final/admin/categories" class="btn btn-primary">Licences</a>

<!-- Lien vers la liste des produits -->
<p class="my-3">Clique ici pour modifier la liste des produits</p>
<a href="/res03-projet-final/admin/products" class="btn btn-primary">Produits</a>

<!-- Lien vers la liste des utilisateurs -->
<p class="my-3">Clique ici pour modifier la liste des utilisateurs</p>
<a href="/res03-projet-final/admin/users" class="btn btn-primary">Utilisateurs</a>

<!-- Lien vers la liste des commandes -->
<p class="my-3">Clique ici pour modifier la liste des commandes</p>
<a href="/res03-projet-final/admin/orders" class="btn btn-primary">Commandes</a>

<!-- Lien vers la page d'accueil -->
<a href="/res03-projet-final/accueil">Page d'accueil</a>
