<h1>Contact</h1>
<p>Si tu as des questions concernant tes achats, où sur l'expédition n'hésite pas à me contacter sur mes réseaux</p>
<section>
    <span class="fa-brands fa-facebook"></span>
    <span class="fa-brands fa-facebook-messenger"></span>
    <span class="fa-brands fa-instagram"></span>
    <span class="fa-brands fa-snapchat"></span>
    <span class="fa-brands fa-tiktok" style="color: #1e3050;"></span>
</section>
