<h1>Informations</h1>

<section>
    <h2>Affichage des infos</h2>
    <p>Bienvenue sur mon site !</p>
    <p>Bienvenue sur mon projet réalisé pour valider ma formation de développeur full-stack à la 3W Academy de Rennes.</p>
    <p>Ayant découvert, depuis maintenant 2 ans, ma passion des animés/mangas et de l'univers japonais, j'ai décidé de créer un site de e-commerce de produit en rapport avec les plus grandes licences des animés/mangas (je suis désolé si j'en ai oublié).</p>
    <p>Je vous souhaite une bonne navigation !</p>
    
    <!-- Bouton de redirection vers la liste des catégories -->
    <p><a href="/res03-projet-final/liste-categories">Commencer à naviguer</a></p>
    
</section>