<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <title>Projet Final</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&family=Stick+No+Bills&family=Wallpoet&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/res03-projet-final/assets/styles/css/style.css" />
</head>
    <body class="cart-open" id= <?php echo $template ?> >
    
    
    <?php
    if($_SESSION) {
        require 'partials/_userHeader.phtml';
    }
    
    else {
        require 'partials/_header.phtml';
    } ?>
    
    <main>
        
        <?php require "templates/".$template."/".$template.".phtml"; ?>
        
    </main>
    <aside>
        <header>
            <h2>Mon panier</h2>
            <p id="cart-total-price">Total : 59 $</p>
        </header>
        <main>
            <ul>

            </ul>
        </main>
        <footer>
            <a class="btn btn-cart-back" href="/res03-projet-final/liste-categories">Continuer mes achats</a>
            <a class="btn btn-cart-order" href="/res03-projet-final/panier">Finaliser la commande</a>
        </footer>
    </aside>
    
    <?php require 'partials/_footer.phtml'; ?>
    
    <script type="module" src="/res03-projet-final/assets/javascript/main.js"></script>
    
    </body>
</html>