<h1>Formulaire de création d'un produit</h1>

<form method="post" action="admin-products-create">
    <fieldset>
        <label for="name">Nom</label>
        <input type="text" name="name" id="name" />
    </fieldset>
    <fieldset>
        <label for="description">Description</label>
        <textarea name="description" rows="5" cols="30" placeholder="Décris le produit"></textarea>
    </fieldset>
    <fieldset>
        <label for="number">Prix</label>
        <input type="text" name="price" id="price" />
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" value="products">
    </fieldset>
    <fieldset>
        <input type="submit" value="Je crée le produit" />
    </fieldset>
</form>