<h1>Formulaire de création de catégorie</h1>

<form method="post" action="/res03-projet-final/admin/categories/create">
    <fieldset>
        <label for="title">Titre</label>
        <input type="text" class="form-control" name="title" id="title" />
    </fieldset>
    <fieldset>
        <label for="description">Description</label>
        <textarea name="description" rows="5" cols="100"></textarea>
    </fieldset>
    <fieldset>
        <label for="URL-icone">Icone</label>
        <input type="text" class="form-control" name="URL-icone" id="URL-icone" />
    </fieldset>
    <fieldset>
        <label for="caption-icone">Caption Icone</label>
        <input type="text" class="form-control" name="caption-icone" id="caption-icone" />
    </fieldset>
    <fieldset>
        <label for="URL-logo">Logo</label>
        <input type="text" class="form-control" name="URL-logo" id="URL-logo" />
    </fieldset>
    <fieldset>
        <label for="caption-logo">Caption Logo</label>
        <input type="text" class="form-control" name="caption-logo" id="caption-logo" />
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" value="create-category">
    </fieldset>
    <fieldset>
        <input type="submit" value="Je crée la licence" />
    </fieldset>
</form>